[package]
name = "pmc-sys"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
build = "build.rs"

[lib]
name = "pmc_sys"

[build-dependencies]
bindgen = "0.33"

[dependencies]
libc = "0.2"